# EMAIL PLUGIN BY MIKE724
# LICENSED UNDER THE GPLv3
# SOURCE CODE AVAILABLE ON GITHUB:
# https://github.com/Mike724/Email
# VIEW MY WEBSITE AT:
# www.mike724.com
# -------------------------------------------------------------------------------------------------
# language -- the language you wish to use
#             valid languages: English, French, German, German_paraphrase, Spanish
# -------------------------------------------------------------------------------------------------
# EMAIL
# enable - whether or not to enable email sending
# type - the provider type defined in the providers configuration section
# user - your email
# password - obviously, this is your email's password.
# -- Email data alterations (alter)
# subject - The subject of the email
# content - The content of the email (body)
# in_between_pages - What to separate book pages with (default is a space)
# -- Alteration variables:
# $BOOK_TITLE - The title of the book (by default used as the email's subject)
# $BOOK_CONTENT -The content of all the pages in the book (by default used as the email's content)
# $PLAYER_NAME - The name of the player who is sending the email
# $NL - Used to make a new line
# -------------------------------------------------------------------------------------------------
# PROVIDERS
# GMAIL - Settings for sending email with Gmail
# HOTMAIL - Settings for sending email with Hotmail
# Add your own providers too!
# If it's a popular one, submit it to me so I can include it for others!
# You can view available settings here:
# http://javamail.kenai.com/nonav/javadocs/com/sun/mail/smtp/package-summary.html
# $PASS will be replaced with your password (probably not needed, included just in case)
language: English
email:
  enable: false
  type: GMAIL
  user: emailhere@gmail.com
  password: emailPasswordHere
  alter:
    sender_email_given:
      yes: You can reply to $PLAYER_NAME at $PLAYER_EMAIL.
      no: ''
    subject: $BOOK_TITLE
    content: $BOOK_CONTENT$NL$NLThis email was sent to you by $PLAYER_NAME.$SENDER_EMAIL_GIVEN
    in_between_pages: ' '
rewards:
  enable: false
  money: 25
  items:
    - id: 1
      damage: 0
    - id: 35
      damage: 6
providers:
  GMAIL:
    - mail.smtp.host: smtp.gmail.com
    - mail.smtp.socketFactory.port: 465
    - mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    - mail.smtp.auth: true
    - mail.smtp.socketFactory.fallback: false
    - mail.smtp.port: 465
  HOTMAIL:
    - mail.smtp.host: smtp.live.com
    - mail.smtp.socketFactory.port: 25
    - mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    - mail.smtp.auth: true
    - mail.smtp.socketFactory.fallback: false
    - mail.smtp.port: 25
