name: Email
main: com.mike724.email.Email
author: Mike724 & MainTurboCraft
version: ${version}
commands:
    email:
        aliases: [e, em]
        description: Manage your email entry
        usage: /<command> help