name: Email
main: com.mike724.email.Email
authors: [Mike724, MainTurboCraft]
version: ${version}
commands:
    email:
        aliases: [e, em]
        description: Manage your email entry and send emails
        usage: /<command> help
